[package]
name = "RuneFactory3SpecialInternalTrainer"
version = "0.4.1"
edition = "2021"
authors = ["vsylva"]
publish = false
license = "MIT"

[lib]
name = "xinput1_4"
crate-type = ["cdylib"]

[dependencies]
hudhook = { git = "https://github.com/veeenu/hudhook.git", rev = "9c78aa5", default-features = false, features = [
    "dx11",
] }
libmem = "5.0.1"
strum = "0.26.3"
strum_macros = "0.26.4"
unsafe_fn_body = "0.1.3"

[build-dependencies]
forward-dll = "0.1.16"
