[package]
name = "rune_factory3_trainer"
version = "0.3.2"
edition = "2021"
authors = ["sylvavv"]
publish = false
license = "MIT"

[lib]
name = "xinput1_4"
crate-type = ["cdylib"]

[dependencies]
libmem = "5.0.1"
minhook_raw = "0.3.0"
hudhook = { git = "https://github.com/veeenu/hudhook.git", rev = "9c78aa5", default-features = false, features = [
    "dx11",
] }
strum = "0.26.3"
strum_macros = "0.26.4"

[build-dependencies]
forward-dll = "0.1.16"
